#bind-address: log.socket
bind-address: !!python/tuple ["::", 5514]

#receivers: 1
receivers: 4

#senders: 1
senders: 8

queue-size: 1000000

elasticsearch:
  urls:
      - http://elastic0.i.fog.yandex.net:9200
      - http://elastic1.i.fog.yandex.net:9200
      - http://node01d.elasticlog.yandex.net:9200
      - http://node02d.elasticlog.yandex.net:9200

  #bulksize: 1
  bulksize: 10000

  #index: log-{@timestamp:%Y}-{@timestamp:%m}-{@timestamp:%d}
  index: debug-{@timestamp:%Y}-{@timestamp:%m}-{@timestamp:%d}

graphite:
  host: graphite-shard1.i.fog.yandex.net
  port: 2024
  group: yasd-zbx

logging:
  version: 1
  handlers:
    syslog:
      class: logging.handlers.SysLogHandler
      address: /dev/log
      formatter: syslog
      level: ERROR
    stderr:
      class: logging.StreamHandler
      stream: ext://sys.stderr
      formatter: stderr
  loggers:
    pyelasticsearch:
      level: INFO
    graphitesend:
      level: INFO
    yasd:
      level: INFO
  formatters:
    syslog:
      format: '%(asctime)s yasd[%(process)d]: %(message)s'
      datefmt: '%b %e %H:%M:%S'
    stderr:
      format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'
  root:
    handlers:
      - syslog
      - stderr
    level: INFO

