#!/usr/bin/env python

import logging
import logging.handlers
import yasd

if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG)
    handler = logging.handlers.SysLogHandler(address='/dev/log')
    handler.setLevel(logging.INFO)
    handler.setFormatter(logging.Formatter('%(asctime)s yasd[%(process)d]: %(message)s', '%b %e %H:%M:%S'))
    logging.getLogger().addHandler(handler)
    #logging.getLogger('pyelasticsearch').setLevel(logging.DEBUG)
    logging.getLogger('graphitesend').setLevel(logging.INFO)
    logging.TRACE = 5
    yasd.unix_to_elastic()
    logging.info('started')
